version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: aIhqBYcC472juVMQD5dvJft55TBSz9nsQ
before_build:
- ps: nuget restore ./Balkan Air/Balkan Air.sln
build:
  project: ./Balkan Air/Balkan Air.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - itplamen@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
